import { Injectable } from '@angular/core';
import {
  EmployeeData,
  EmployeeListFilter,
  EmployeePaginatedData,
} from '../../models/employee.model';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class EmployeeService {
  private employees: EmployeeData[] = [
    {
      username: 'sitiwijaya1',
      firstName: 'Siti',
      lastName: 'Wijaya',
      email: 'sitiwijaya1@example.com',
      birthDate: new Date('1988-07-15'),
      basicSalary: 18544321,
      status: 'Active',
      group: 'Engineering',
      description: new Date('2015-02-21'),
    },
    {
      username: 'agusnugroho2',
      firstName: 'Agus',
      lastName: 'Nugroho',
      email: 'agusnugroho2@example.com',
      birthDate: new Date('1995-03-10'),
      basicSalary: 7890123,
      status: 'Active',
      group: 'Product Development',
      description: new Date('2022-08-11'),
    },
    {
      username: 'putrisantoso3',
      firstName: 'Putri',
      lastName: 'Santoso',
      email: 'putrisantoso3@example.com',
      birthDate: new Date('1992-11-25'),
      basicSalary: 12345678,
      status: 'On Leave',
      group: 'Sales & Marketing',
      description: new Date('2019-05-30'),
    },
    {
      username: 'jokohartono4',
      firstName: 'Joko',
      lastName: 'Hartono',
      email: 'jokohartono4@example.com',
      birthDate: new Date('1985-01-05'),
      basicSalary: 19876543,
      status: 'Active',
      group: 'Operations',
      description: new Date('2012-12-12'),
    },
    {
      username: 'dewisaputra5',
      firstName: 'Dewi',
      lastName: 'Saputra',
      email: 'dewisaputra5@example.com',
      birthDate: new Date('1998-09-18'),
      basicSalary: 6543210,
      status: 'Terminated',
      group: 'Customer Success',
      description: new Date('2023-01-15'),
    },
    {
      username: 'bambanggunawan6',
      firstName: 'Bambang',
      lastName: 'Gunawan',
      email: 'bambanggunawan6@example.com',
      birthDate: new Date('1983-04-22'),
      basicSalary: 14500000,
      status: 'Active',
      group: 'Finance & Accounting',
      description: new Date('2011-06-01'),
    },
    {
      username: 'srisetiawan7',
      firstName: 'Sri',
      lastName: 'Setiawan',
      email: 'srisetiawan7@example.com',
      birthDate: new Date('1991-06-30'),
      basicSalary: 16200000,
      status: 'Active',
      group: 'Information Technology',
      description: new Date('2018-03-19'),
    },
    {
      username: 'adisusanto8',
      firstName: 'Adi',
      lastName: 'Susanto',
      email: 'adisusanto8@example.com',
      birthDate: new Date('1989-12-01'),
      basicSalary: 11000000,
      status: 'Active',
      group: 'Legal & Compliance',
      description: new Date('2017-10-05'),
    },
    {
      username: 'indahprakoso9',
      firstName: 'Indah',
      lastName: 'Prakoso',
      email: 'indahprakoso9@example.com',
      birthDate: new Date('1996-02-14'),
      basicSalary: 9500000,
      status: 'On Leave',
      group: 'Research & Development',
      description: new Date('2021-04-20'),
    },
    {
      username: 'rizkysalim10',
      firstName: 'Rizky',
      lastName: 'Salim',
      email: 'rizkysalim10@example.com',
      birthDate: new Date('1993-08-08'),
      basicSalary: 13800000,
      status: 'Active',
      group: 'Executive Leadership',
      description: new Date('2020-11-28'),
    },
    {
      username: 'ahmadwibowo11',
      firstName: 'Ahmad',
      lastName: 'Wibowo',
      email: 'ahmadwibowo11@example.com',
      birthDate: new Date('1981-05-19'),
      basicSalary: 17800000,
      status: 'Active',
      group: 'Engineering',
      description: new Date('2010-09-14'),
    },
    {
      username: 'anikusuma12',
      firstName: 'Ani',
      lastName: 'Kusuma',
      email: 'anikusuma12@example.com',
      birthDate: new Date('1999-07-23'),
      basicSalary: 5800000,
      status: 'Active',
      group: 'Product Development',
      description: new Date('2023-06-05'),
    },
    {
      username: 'agungpurnama13',
      firstName: 'Agung',
      lastName: 'Purnama',
      email: 'agungpurnama13@example.com',
      birthDate: new Date('1986-10-03'),
      basicSalary: 15500000,
      status: 'Active',
      group: 'Sales & Marketing',
      description: new Date('2013-07-22'),
    },
    {
      username: 'lestariprakoso14',
      firstName: 'Lestari',
      lastName: 'Prakoso',
      email: 'lestariprakoso14@example.com',
      birthDate: new Date('1994-01-29'),
      basicSalary: 10500000,
      status: 'Active',
      group: 'Operations',
      description: new Date('2016-01-18'),
    },
    {
      username: 'ekosurya15',
      firstName: 'Eko',
      lastName: 'Surya',
      email: 'ekosurya15@example.com',
      birthDate: new Date('1982-03-12'),
      basicSalary: 16900000,
      status: 'Terminated',
      group: 'Customer Success',
      description: new Date('2014-04-09'),
    },
    {
      username: 'rinahidayat16',
      firstName: 'Rina',
      lastName: 'Hidayat',
      email: 'rinahidayat16@example.com',
      birthDate: new Date('1997-05-01'),
      basicSalary: 8800000,
      status: 'Active',
      group: 'Finance & Accounting',
      description: new Date('2020-02-03'),
    },
    {
      username: 'muhammadsantoso17',
      firstName: 'Muhammad',
      lastName: 'Santoso',
      email: 'muhammadsantoso17@example.com',
      birthDate: new Date('1987-11-07'),
      basicSalary: 14200000,
      status: 'Active',
      group: 'Information Technology',
      description: new Date('2016-11-16'),
    },
    {
      username: 'diansaputra18',
      firstName: 'Dian',
      lastName: 'Saputra',
      email: 'diansaputra18@example.com',
      birthDate: new Date('1990-09-09'),
      basicSalary: 12800000,
      status: 'Active',
      group: 'Legal & Compliance',
      description: new Date('2018-07-07'),
    },
    {
      username: 'sarihartono19',
      firstName: 'Sari',
      lastName: 'Hartono',
      email: 'sarihartono19@example.com',
      birthDate: new Date('2000-08-20'),
      basicSalary: 5100000,
      status: 'Active',
      group: 'Research & Development',
      description: new Date('2023-09-01'),
    },
    {
      username: 'budiwijaya20',
      firstName: 'Budi',
      lastName: 'Wijaya',
      email: 'budiwijaya20@example.com',
      birthDate: new Date('1984-06-28'),
      basicSalary: 19500000,
      status: 'Active',
      group: 'Executive Leadership',
      description: new Date('2011-03-25'),
    },
    {
      username: 'sitiwijaya21',
      firstName: 'Siti',
      lastName: 'Wijaya',
      email: 'sitiwijaya21@example.com',
      birthDate: new Date('1998-09-17'),
      basicSalary: 14755102,
      status: 'Active',
      group: 'Engineering',
      description: new Date('2012-04-16'),
    },
    {
      username: 'muhammadprakoso22',
      firstName: 'Muhammad',
      lastName: 'Prakoso',
      email: 'muhammadprakoso22@example.com',
      birthDate: new Date('1982-11-20'),
      basicSalary: 14781488,
      status: 'Active',
      group: 'Product Development',
      description: new Date('2014-07-02'),
    },
    {
      username: 'jokohartono23',
      firstName: 'Joko',
      lastName: 'Hartono',
      email: 'jokohartono23@example.com',
      birthDate: new Date('1986-09-24'),
      basicSalary: 13958744,
      status: 'On Leave',
      group: 'Sales & Marketing',
      description: new Date('2019-02-09'),
    },
    {
      username: 'dianhartono24',
      firstName: 'Dian',
      lastName: 'Hartono',
      email: 'dianhartono24@example.com',
      birthDate: new Date('1986-06-03'),
      basicSalary: 19371764,
      status: 'Active',
      group: 'Operations',
      description: new Date('2023-01-20'),
    },
    {
      username: 'bambangsalim25',
      firstName: 'Bambang',
      lastName: 'Salim',
      email: 'bambangsalim25@example.com',
      birthDate: new Date('1995-10-21'),
      basicSalary: 18919426,
      status: 'Active',
      group: 'Customer Success',
      description: new Date('2022-09-17'),
    },
    {
      username: 'indahsusanto26',
      firstName: 'Indah',
      lastName: 'Susanto',
      email: 'indahsusanto26@example.com',
      birthDate: new Date('1982-05-18'),
      basicSalary: 5698387,
      status: 'Terminated',
      group: 'Finance & Accounting',
      description: new Date('2017-09-11'),
    },
    {
      username: 'putrihidayat27',
      firstName: 'Putri',
      lastName: 'Hidayat',
      email: 'putrihidayat27@example.com',
      birthDate: new Date('1996-05-02'),
      basicSalary: 18278284,
      status: 'On Leave',
      group: 'Information Technology',
      description: new Date('2022-05-08'),
    },
    {
      username: 'jokowibowo28',
      firstName: 'Joko',
      lastName: 'Wibowo',
      email: 'jokowibowo28@example.com',
      birthDate: new Date('1982-12-07'),
      basicSalary: 11528646,
      status: 'Active',
      group: 'Legal & Compliance',
      description: new Date('2020-01-25'),
    },
    {
      username: 'agungprakoso29',
      firstName: 'Agung',
      lastName: 'Prakoso',
      email: 'agungprakoso29@example.com',
      birthDate: new Date('1997-03-24'),
      basicSalary: 11059535,
      status: 'Terminated',
      group: 'Research & Development',
      description: new Date('2013-09-21'),
    },
    {
      username: 'srinugroho30',
      firstName: 'Sri',
      lastName: 'Nugroho',
      email: 'srinugroho30@example.com',
      birthDate: new Date('1994-01-14'),
      basicSalary: 12287948,
      status: 'On Leave',
      group: 'Executive Leadership',
      description: new Date('2016-09-08'),
    },
    {
      username: 'budiwijaya31',
      firstName: 'Budi',
      lastName: 'Wijaya',
      email: 'budiwijaya31@example.com',
      birthDate: new Date('1980-03-04'),
      basicSalary: 19803867,
      status: 'Active',
      group: 'Engineering',
      description: new Date('2010-01-09'),
    },
    {
      username: 'rinawijaya32',
      firstName: 'Rina',
      lastName: 'Wijaya',
      email: 'rinawijaya32@example.com',
      birthDate: new Date('1983-05-24'),
      basicSalary: 19446211,
      status: 'Active',
      group: 'Product Development',
      description: new Date('2021-06-25'),
    },
    {
      username: 'ahmadpurnama33',
      firstName: 'Ahmad',
      lastName: 'Purnama',
      email: 'ahmadpurnama33@example.com',
      birthDate: new Date('1992-06-13'),
      basicSalary: 6476831,
      status: 'Terminated',
      group: 'Sales & Marketing',
      description: new Date('2017-02-12'),
    },
    {
      username: 'ekosusanto34',
      firstName: 'Eko',
      lastName: 'Susanto',
      email: 'ekosusanto34@example.com',
      birthDate: new Date('1997-02-11'),
      basicSalary: 7887321,
      status: 'Active',
      group: 'Operations',
      description: new Date('2015-01-14'),
    },
    {
      username: 'dewihartono35',
      firstName: 'Dewi',
      lastName: 'Hartono',
      email: 'dewihartono35@example.com',
      birthDate: new Date('1998-05-22'),
      basicSalary: 12056286,
      status: 'Active',
      group: 'Customer Success',
      description: new Date('2011-04-03'),
    },
    {
      username: 'sitinugroho36',
      firstName: 'Siti',
      lastName: 'Nugroho',
      email: 'sitinugroho36@example.com',
      birthDate: new Date('1998-04-01'),
      basicSalary: 19335686,
      status: 'Terminated',
      group: 'Finance & Accounting',
      description: new Date('2010-09-02'),
    },
    {
      username: 'agussantoso37',
      firstName: 'Agus',
      lastName: 'Santoso',
      email: 'agussantoso37@example.com',
      birthDate: new Date('1997-04-20'),
      basicSalary: 12822176,
      status: 'On Leave',
      group: 'Information Technology',
      description: new Date('2020-03-22'),
    },
    {
      username: 'lestaripurnama38',
      firstName: 'Lestari',
      lastName: 'Purnama',
      email: 'lestaripurnama38@example.com',
      birthDate: new Date('1991-03-01'),
      basicSalary: 18271798,
      status: 'Terminated',
      group: 'Legal & Compliance',
      description: new Date('2021-12-04'),
    },
    {
      username: 'bambanggunawan39',
      firstName: 'Bambang',
      lastName: 'Gunawan',
      email: 'bambanggunawan39@example.com',
      birthDate: new Date('1988-12-07'),
      basicSalary: 17894236,
      status: 'Active',
      group: 'Research & Development',
      description: new Date('2014-06-21'),
    },
    {
      username: 'sarikusuma40',
      firstName: 'Sari',
      lastName: 'Kusuma',
      email: 'sarikusuma40@example.com',
      birthDate: new Date('1992-06-25'),
      basicSalary: 6280453,
      status: 'Active',
      group: 'Executive Leadership',
      description: new Date('2014-11-20'),
    },
    {
      username: 'adisusanto41',
      firstName: 'Adi',
      lastName: 'Susanto',
      email: 'adisusanto41@example.com',
      birthDate: new Date('1983-04-18'),
      basicSalary: 12479269,
      status: 'Active',
      group: 'Engineering',
      description: new Date('2019-12-25'),
    },
    {
      username: 'muhammadprakoso42',
      firstName: 'Muhammad',
      lastName: 'Prakoso',
      email: 'muhammadprakoso42@example.com',
      birthDate: new Date('1995-10-21'),
      basicSalary: 6241042,
      status: 'On Leave',
      group: 'Product Development',
      description: new Date('2011-03-24'),
    },
    {
      username: 'anipurnama43',
      firstName: 'Ani',
      lastName: 'Purnama',
      email: 'anipurnama43@example.com',
      birthDate: new Date('1988-03-12'),
      basicSalary: 5678453,
      status: 'Terminated',
      group: 'Sales & Marketing',
      description: new Date('2010-09-03'),
    },
    {
      username: 'srisetiawan44',
      firstName: 'Sri',
      lastName: 'Setiawan',
      email: 'srisetiawan44@example.com',
      birthDate: new Date('1983-05-18'),
      basicSalary: 15462803,
      status: 'Active',
      group: 'Operations',
      description: new Date('2020-03-26'),
    },
    {
      username: 'rinanugroho45',
      firstName: 'Rina',
      lastName: 'Nugroho',
      email: 'rinanugroho45@example.com',
      birthDate: new Date('1994-06-03'),
      basicSalary: 16904664,
      status: 'Terminated',
      group: 'Customer Success',
      description: new Date('2013-09-02'),
    },
    {
      username: 'ahmadhartono46',
      firstName: 'Ahmad',
      lastName: 'Hartono',
      email: 'ahmadhartono46@example.com',
      birthDate: new Date('1997-12-07'),
      basicSalary: 19692484,
      status: 'Active',
      group: 'Finance & Accounting',
      description: new Date('2023-01-20'),
    },
    {
      username: 'rizkysantoso47',
      firstName: 'Rizky',
      lastName: 'Santoso',
      email: 'rizkysantoso47@example.com',
      birthDate: new Date('1983-01-21'),
      basicSalary: 14092144,
      status: 'Active',
      group: 'Information Technology',
      description: new Date('2022-03-01'),
    },
    {
      username: 'jokohartono48',
      firstName: 'Joko',
      lastName: 'Hartono',
      email: 'jokohartono48@example.com',
      birthDate: new Date('1999-07-28'),
      basicSalary: 13955615,
      status: 'Active',
      group: 'Legal & Compliance',
      description: new Date('2020-04-18'),
    },
    {
      username: 'lestaripurnama49',
      firstName: 'Lestari',
      lastName: 'Purnama',
      email: 'lestaripurnama49@example.com',
      birthDate: new Date('1996-03-24'),
      basicSalary: 18231580,
      status: 'Active',
      group: 'Research & Development',
      description: new Date('2010-09-01'),
    },
    {
      username: 'ekosusanto50',
      firstName: 'Eko',
      lastName: 'Susanto',
      email: 'ekosusanto50@example.com',
      birthDate: new Date('1993-01-23'),
      basicSalary: 18683525,
      status: 'Terminated',
      group: 'Executive Leadership',
      description: new Date('2013-08-01'),
    },
    {
      username: 'dianhidayat51',
      firstName: 'Dian',
      lastName: 'Hidayat',
      email: 'dianhidayat51@example.com',
      birthDate: new Date('1990-07-26'),
      basicSalary: 6059635,
      status: 'Active',
      group: 'Engineering',
      description: new Date('2010-06-13'),
    },
    {
      username: 'agungprakoso52',
      firstName: 'Agung',
      lastName: 'Prakoso',
      email: 'agungprakoso52@example.com',
      birthDate: new Date('1997-12-07'),
      basicSalary: 12693892,
      status: 'Active',
      group: 'Product Development',
      description: new Date('2020-05-23'),
    },
    {
      username: 'putrihidayat53',
      firstName: 'Putri',
      lastName: 'Hidayat',
      email: 'putrihidayat53@example.com',
      birthDate: new Date('1983-11-20'),
      basicSalary: 19488424,
      status: 'Terminated',
      group: 'Sales & Marketing',
      description: new Date('2021-03-23'),
    },
    {
      username: 'sarikusuma54',
      firstName: 'Sari',
      lastName: 'Kusuma',
      email: 'sarikusuma54@example.com',
      birthDate: new Date('1989-10-14'),
      basicSalary: 9239843,
      status: 'On Leave',
      group: 'Operations',
      description: new Date('2013-09-02'),
    },
    {
      username: 'bambangsalim55',
      firstName: 'Bambang',
      lastName: 'Salim',
      email: 'bambangsalim55@example.com',
      birthDate: new Date('1994-11-21'),
      basicSalary: 18451700,
      status: 'Active',
      group: 'Customer Success',
      description: new Date('2015-08-01'),
    },
    {
      username: 'sriwijaya56',
      firstName: 'Sri',
      lastName: 'Wijaya',
      email: 'sriwijaya56@example.com',
      birthDate: new Date('1986-07-06'),
      basicSalary: 14931327,
      status: 'Active',
      group: 'Finance & Accounting',
      description: new Date('2021-05-18'),
    },
    {
      username: 'indahprakoso57',
      firstName: 'Indah',
      lastName: 'Prakoso',
      email: 'indahprakoso57@example.com',
      birthDate: new Date('1983-09-17'),
      basicSalary: 10580970,
      status: 'Active',
      group: 'Information Technology',
      description: new Date('2018-05-09'),
    },
    {
      username: 'agussantoso58',
      firstName: 'Agus',
      lastName: 'Santoso',
      email: 'agussantoso58@example.com',
      birthDate: new Date('1994-06-25'),
      basicSalary: 6398906,
      status: 'Terminated',
      group: 'Legal & Compliance',
      description: new Date('2018-07-26'),
    },
    {
      username: 'budiwibowo59',
      firstName: 'Budi',
      lastName: 'Wibowo',
      email: 'budiwibowo59@example.com',
      birthDate: new Date('1999-01-26'),
      basicSalary: 11099684,
      status: 'Terminated',
      group: 'Research & Development',
      description: new Date('2019-02-12'),
    },
    {
      username: 'dewisaputra60',
      firstName: 'Dewi',
      lastName: 'Saputra',
      email: 'dewisaputra60@example.com',
      birthDate: new Date('1987-10-14'),
      basicSalary: 19483038,
      status: 'Active',
      group: 'Executive Leadership',
      description: new Date('2014-07-16'),
    },
    {
      username: 'anikusuma61',
      firstName: 'Ani',
      lastName: 'Kusuma',
      email: 'anikusuma61@example.com',
      birthDate: new Date('1987-03-01'),
      basicSalary: 11339891,
      status: 'Active',
      group: 'Engineering',
      description: new Date('2017-06-25'),
    },
    {
      username: 'agungprakoso62',
      firstName: 'Agung',
      lastName: 'Prakoso',
      email: 'agungprakoso62@example.com',
      birthDate: new Date('1993-02-09'),
      basicSalary: 9037041,
      status: 'Active',
      group: 'Product Development',
      description: new Date('2012-07-06'),
    },
    {
      username: 'rinawijaya63',
      firstName: 'Rina',
      lastName: 'Wijaya',
      email: 'rinawijaya63@example.com',
      birthDate: new Date('1995-10-18'),
      basicSalary: 17878848,
      status: 'Active',
      group: 'Sales & Marketing',
      description: new Date('2023-01-20'),
    },
    {
      username: 'muhammadpurnama64',
      firstName: 'Muhammad',
      lastName: 'Purnama',
      email: 'muhammadpurnama64@example.com',
      birthDate: new Date('1993-01-09'),
      basicSalary: 17409257,
      status: 'Terminated',
      group: 'Operations',
      description: new Date('2010-09-02'),
    },
    {
      username: 'lestaripurnama65',
      firstName: 'Lestari',
      lastName: 'Purnama',
      email: 'lestaripurnama65@example.com',
      birthDate: new Date('1988-02-14'),
      basicSalary: 17658744,
      status: 'Active',
      group: 'Customer Success',
      description: new Date('2019-12-04'),
    },
    {
      username: 'rizkyhartono66',
      firstName: 'Rizky',
      lastName: 'Hartono',
      email: 'rizkyhartono66@example.com',
      birthDate: new Date('1983-09-24'),
      basicSalary: 18278284,
      status: 'Active',
      group: 'Finance & Accounting',
      description: new Date('2016-11-20'),
    },
    {
      username: 'adisusanto67',
      firstName: 'Adi',
      lastName: 'Susanto',
      email: 'adisusanto67@example.com',
      birthDate: new Date('1985-05-18'),
      basicSalary: 13958744,
      status: 'Active',
      group: 'Information Technology',
      description: new Date('2012-07-20'),
    },
    {
      username: 'agungpurnama68',
      firstName: 'Agung',
      lastName: 'Purnama',
      email: 'agungpurnama68@example.com',
      birthDate: new Date('1991-04-18'),
      basicSalary: 13745019,
      status: 'On Leave',
      group: 'Legal & Compliance',
      description: new Date('2010-01-09'),
    },
    {
      username: 'bambangsalim69',
      firstName: 'Bambang',
      lastName: 'Salim',
      email: 'bambangsalim69@example.com',
      birthDate: new Date('1990-09-02'),
      basicSalary: 17873284,
      status: 'Active',
      group: 'Research & Development',
      description: new Date('2015-02-14'),
    },
    {
      username: 'ekosusanto70',
      firstName: 'Eko',
      lastName: 'Susanto',
      email: 'ekosusanto70@example.com',
      birthDate: new Date('1988-12-04'),
      basicSalary: 19488424,
      status: 'Terminated',
      group: 'Executive Leadership',
      description: new Date('2017-09-11'),
    },
    {
      username: 'sarihidayat71',
      firstName: 'Sari',
      lastName: 'Hidayat',
      email: 'sarihidayat71@example.com',
      birthDate: new Date('1983-05-01'),
      basicSalary: 12822176,
      status: 'Active',
      group: 'Engineering',
      description: new Date('2012-07-20'),
    },
    {
      username: 'jokohartono72',
      firstName: 'Joko',
      lastName: 'Hartono',
      email: 'jokohartono72@example.com',
      birthDate: new Date('1986-07-26'),
      basicSalary: 11339891,
      status: 'Active',
      group: 'Product Development',
      description: new Date('2014-06-21'),
    },
    {
      username: 'sitinugroho73',
      firstName: 'Siti',
      lastName: 'Nugroho',
      email: 'sitinugroho73@example.com',
      birthDate: new Date('1994-01-21'),
      basicSalary: 15462803,
      status: 'Terminated',
      group: 'Sales & Marketing',
      description: new Date('2019-12-04'),
    },
    {
      username: 'ahmadpurnama74',
      firstName: 'Ahmad',
      lastName: 'Purnama',
      email: 'ahmadpurnama74@example.com',
      birthDate: new Date('1991-03-01'),
      basicSalary: 19692484,
      status: 'Active',
      group: 'Operations',
      description: new Date('2018-05-09'),
    },
    {
      username: 'budiwibowo75',
      firstName: 'Budi',
      lastName: 'Wibowo',
      email: 'budiwibowo75@example.com',
      birthDate: new Date('1999-01-26'),
      basicSalary: 18271798,
      status: 'Active',
      group: 'Customer Success',
      description: new Date('2011-04-03'),
    },
    {
      username: 'putrihidayat76',
      firstName: 'Putri',
      lastName: 'Hidayat',
      email: 'putrihidayat76@example.com',
      birthDate: new Date('1992-06-25'),
      basicSalary: 13955615,
      status: 'On Leave',
      group: 'Finance & Accounting',
      description: new Date('2010-09-02'),
    },
    {
      username: 'dianhartono77',
      firstName: 'Dian',
      lastName: 'Hartono',
      email: 'dianhartono77@example.com',
      birthDate: new Date('1983-11-20'),
      basicSalary: 12287948,
      status: 'Active',
      group: 'Information Technology',
      description: new Date('2013-08-01'),
    },
    {
      username: 'agungprakoso78',
      firstName: 'Agung',
      lastName: 'Prakoso',
      email: 'agungprakoso78@example.com',
      birthDate: new Date('1988-12-04'),
      basicSalary: 11099684,
      status: 'Active',
      group: 'Legal & Compliance',
      description: new Date('2019-02-12'),
    },
    {
      username: 'agusnugroho79',
      firstName: 'Agus',
      lastName: 'Nugroho',
      email: 'agusnugroho79@example.com',
      birthDate: new Date('1996-03-24'),
      basicSalary: 9239843,
      status: 'Active',
      group: 'Research & Development',
      description: new Date('2020-05-23'),
    },
    {
      username: 'bambanggunawan80',
      firstName: 'Bambang',
      lastName: 'Gunawan',
      email: 'bambanggunawan80@example.com',
      birthDate: new Date('1998-04-01'),
      basicSalary: 10580970,
      status: 'Terminated',
      group: 'Executive Leadership',
      description: new Date('2014-07-16'),
    },
    {
      username: 'indahsusanto81',
      firstName: 'Indah',
      lastName: 'Susanto',
      email: 'indahsusanto81@example.com',
      birthDate: new Date('1982-11-20'),
      basicSalary: 19446211,
      status: 'Active',
      group: 'Engineering',
      description: new Date('2017-02-12'),
    },
    {
      username: 'dewisaputra82',
      firstName: 'Dewi',
      lastName: 'Saputra',
      email: 'dewisaputra82@example.com',
      birthDate: new Date('1998-09-17'),
      basicSalary: 18231580,
      status: 'Active',
      group: 'Product Development',
      description: new Date('2021-06-25'),
    },
    {
      username: 'srisetiawan83',
      firstName: 'Sri',
      lastName: 'Setiawan',
      email: 'srisetiawan83@example.com',
      birthDate: new Date('1988-02-14'),
      basicSalary: 6241042,
      status: 'Active',
      group: 'Sales & Marketing',
      description: new Date('2010-09-01'),
    },
    {
      username: 'rinawijaya84',
      firstName: 'Rina',
      lastName: 'Wijaya',
      email: 'rinawijaya84@example.com',
      birthDate: new Date('1983-04-18'),
      basicSalary: 14755102,
      status: 'On Leave',
      group: 'Operations',
      description: new Date('2016-09-08'),
    },
    {
      username: 'ekosurya85',
      firstName: 'Eko',
      lastName: 'Surya',
      email: 'ekosurya85@example.com',
      birthDate: new Date('1997-02-11'),
      basicSalary: 11059535,
      status: 'Active',
      group: 'Customer Success',
      description: new Date('2015-01-14'),
    },
    {
      username: 'lestaripurnama86',
      firstName: 'Lestari',
      lastName: 'Purnama',
      email: 'lestaripurnama86@example.com',
      birthDate: new Date('1980-03-04'),
      basicSalary: 12056286,
      status: 'Active',
      group: 'Finance & Accounting',
      description: new Date('2010-01-09'),
    },
    {
      username: 'muhammadprakoso87',
      firstName: 'Muhammad',
      lastName: 'Prakoso',
      email: 'muhammadprakoso87@example.com',
      birthDate: new Date('1992-06-13'),
      basicSalary: 14781488,
      status: 'Terminated',
      group: 'Information Technology',
      description: new Date('2014-07-02'),
    },
    {
      username: 'jokohartono88',
      firstName: 'Joko',
      lastName: 'Hartono',
      email: 'jokohartono88@example.com',
      birthDate: new Date('1986-09-24'),
      basicSalary: 19335686,
      status: 'Active',
      group: 'Legal & Compliance',
      description: new Date('2019-02-09'),
    },
    {
      username: 'sitiwijaya89',
      firstName: 'Siti',
      lastName: 'Wijaya',
      email: 'sitiwijaya89@example.com',
      birthDate: new Date('1995-10-21'),
      basicSalary: 18919426,
      status: 'Active',
      group: 'Research & Development',
      description: new Date('2022-09-17'),
    },
    {
      username: 'dianhartono90',
      firstName: 'Dian',
      lastName: 'Hartono',
      email: 'dianhartono90@example.com',
      birthDate: new Date('1986-06-03'),
      basicSalary: 5698387,
      status: 'On Leave',
      group: 'Executive Leadership',
      description: new Date('2017-09-11'),
    },
    {
      username: 'bambangsalim91',
      firstName: 'Bambang',
      lastName: 'Salim',
      email: 'bambangsalim91@example.com',
      birthDate: new Date('1996-05-02'),
      basicSalary: 18278284,
      status: 'Active',
      group: 'Engineering',
      description: new Date('2022-05-08'),
    },
    {
      username: 'indahsusanto92',
      firstName: 'Indah',
      lastName: 'Susanto',
      email: 'indahsusanto92@example.com',
      birthDate: new Date('1982-12-07'),
      basicSalary: 11528646,
      status: 'Terminated',
      group: 'Product Development',
      description: new Date('2020-01-25'),
    },
    {
      username: 'putrihidayat93',
      firstName: 'Putri',
      lastName: 'Hidayat',
      email: 'putrihidayat93@example.com',
      birthDate: new Date('1997-03-24'),
      basicSalary: 11059535,
      status: 'Active',
      group: 'Sales & Marketing',
      description: new Date('2013-09-21'),
    },
    {
      username: 'jokowibowo94',
      firstName: 'Joko',
      lastName: 'Wibowo',
      email: 'jokowibowo94@example.com',
      birthDate: new Date('1994-01-14'),
      basicSalary: 12287948,
      status: 'On Leave',
      group: 'Operations',
      description: new Date('2016-09-08'),
    },
    {
      username: 'agungprakoso95',
      firstName: 'Agung',
      lastName: 'Prakoso',
      email: 'agungprakoso95@example.com',
      birthDate: new Date('1980-03-04'),
      basicSalary: 19803867,
      status: 'Active',
      group: 'Customer Success',
      description: new Date('2010-01-09'),
    },
    {
      username: 'srinugroho96',
      firstName: 'Sri',
      lastName: 'Nugroho',
      email: 'srinugroho96@example.com',
      birthDate: new Date('1983-05-24'),
      basicSalary: 19446211,
      status: 'Active',
      group: 'Finance & Accounting',
      description: new Date('2021-06-25'),
    },
    {
      username: 'budiwijaya97',
      firstName: 'Budi',
      lastName: 'Wijaya',
      email: 'budiwijaya97@example.com',
      birthDate: new Date('1992-06-13'),
      basicSalary: 6476831,
      status: 'Terminated',
      group: 'Information Technology',
      description: new Date('2017-02-12'),
    },
    {
      username: 'rinawijaya98',
      firstName: 'Rina',
      lastName: 'Wijaya',
      email: 'rinawijaya98@example.com',
      birthDate: new Date('1997-02-11'),
      basicSalary: 7887321,
      status: 'Active',
      group: 'Legal & Compliance',
      description: new Date('2015-01-14'),
    },
    {
      username: 'ahmadpurnama99',
      firstName: 'Ahmad',
      lastName: 'Purnama',
      email: 'ahmadpurnama99@example.com',
      birthDate: new Date('1998-05-22'),
      basicSalary: 12056286,
      status: 'Active',
      group: 'Research & Development',
      description: new Date('2011-04-03'),
    },
    {
      username: 'ekosusanto100',
      firstName: 'Eko',
      lastName: 'Susanto',
      email: 'ekosusanto100@example.com',
      birthDate: new Date('1998-04-01'),
      basicSalary: 19335686,
      status: 'Terminated',
      group: 'Executive Leadership',
      description: new Date('2010-09-02'),
    },
  ];

  private groupList: string[] = [
    'Engineering',
    'Product Development',
    'Sales & Marketing',
    'Operations',
    'Customer Success',
    'Finance & Accounting',
    'Information Technology',
    'Legal & Compliance',
    'Research & Development',
    'Executive Leadership',
  ];

  getGroupList() {
    return of(this.groupList);
  }

  getEmployeeList(filter: EmployeeListFilter): Observable<EmployeePaginatedData> {
    var startIndex: number = (filter.pageIndex - 1) * filter.pageSize;
    var lowerFullnameFilter: string | undefined = filter.employeeName?.toLowerCase();
    var filteredData: EmployeeData[] = this.employees
      .filter((emp) => {
        var fullName = `${emp.firstName} ${emp.lastName}`;
        return (
          (lowerFullnameFilter == undefined ||
            fullName.toLowerCase().includes(lowerFullnameFilter)) &&
          (filter.group == undefined || filter.group.length < 1 || emp.group == filter.group)
        );
      })
      .sort((a, b) => {
        if (filter.sortColumn == 'fullName'){
          var aFullName = `${a.firstName} ${a.lastName}`;
          var bFullName = `${b.firstName} ${b.lastName}`;
          var fullNameComparation = aFullName.localeCompare(bFullName);
          return filter.isSortByDesc ? -fullNameComparation : fullNameComparation;
        }
        else{
          var aValue = a[filter.sortColumn as keyof EmployeeData];
          var bValue = b[filter.sortColumn as keyof EmployeeData];
          if(aValue < bValue){
            return filter.isSortByDesc ? 1 : -1;
          }else{
            return filter.isSortByDesc ?-1 : 1;
          }
        }
      });

    var totalData: number = filteredData.length;
    filteredData = filteredData.slice(startIndex, startIndex + filter.pageSize);
    var employeeData = {
      employeeData: filteredData,
      pageIndex: filter.pageIndex,
      pageSize: filter.pageSize,
      totalData: totalData,
      totalPage: Math.ceil(totalData / filter.pageSize),
    };
    return of(employeeData);
  }

  deleteEmployeeByUsername(username: string) {
    var idx = this.employees.findIndex((x) => x.username == username);
    if (idx > -1) {
      this.employees.splice(idx, 1);
      return of({
        message: 'success',
        responseCode: 200,
      });
    }
    return of({
      message: 'not Found',
      responseCode: 404,
    });
  }

  insertNewEmployee(data: EmployeeData) {
    var isDuplicate = this.employees.findIndex((x) => x.username == data.username) > -1;
    if (isDuplicate) {
      return of({
        message: 'Username already exist.',
        responseCode: 500,
      });
    } else {
      this.employees.push(data);
      return of({
        message: 'Success.',
        responseCode: 200,
      });
    }
  }

  editEmployee(data: EmployeeData) {
    var idx = this.employees.findIndex((x) => x.username == data.username);
    if (idx > -1) {
      this.employees[idx] = data;
      return of({
        message: 'Success',
        responseCode: 200,
      });
    } else {
      return of({
        message: 'not Found',
        responseCode: 404,
      });
    }
  }
}
